version: "3.9"

services:
  api:
    build: .
    container_name: knowtica_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://knowtica:knowtica@db:5432/knowtica

  db:
    image: postgres:15
    container_name: knowtica_db
    restart: always
    environment:
      POSTGRES_USER: knowtica
      POSTGRES_PASSWORD: knowtica
      POSTGRES_DB: knowtica
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: